plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.barcodephoto'
version = '0.1.0'

android {
  namespace "expo.modules.barcodephoto"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
}

dependencies {
  // zxing-cpp: leest ook GS1 DataBar (Expanded), die Google ML Kit niet ondersteunt.
  implementation "io.github.zxing-cpp:android:2.3.0"
}
